[package]
name = "pam-canonicalize-user"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "elevate-pam user name normalization module"
publish = false

[lib]
name = "pam_canonicalize_user"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
elevate-pam = { workspace = true }
libc = { workspace = true }
