[package]
name = "pam-pwhistory"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "elevate-pam password history module"
publish = false

[lib]
name = "pam_pwhistory"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
elevate-pam = { workspace = true }
libc = { workspace = true }
