[package]
name = "pam-securetty"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "elevate-pam securetty module"
publish = false

[lib]
name = "pam_securetty"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
elevate-pam = { workspace = true }
libc = { workspace = true }
