[package]
name = "pam-env"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "elevate-pam env module"
publish = false

[lib]
name = "pam_env"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
elevate-pam = { workspace = true }
libc = { workspace = true }
