[package]
name = "pam-xauth"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "elevate-pam X11 authentication key forwarder module"
publish = false

[lib]
name = "pam_xauth"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
elevate-pam = { workspace = true }
libc = { workspace = true }
