[package]
name = "pam-keyinit"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "elevate-pam kernel keyring initialization module"
publish = false

[lib]
name = "pam_keyinit"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
elevate-pam = { workspace = true }
libc = { workspace = true }
